# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'EmojiSalad' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EmojiSalad
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'EmojiSaladTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
