const KEY = '@appqueueMiddleware/';

export const REQUEST_DEVICE_INFO = `${KEY}REQUEST_DEVICE_INFO`;
export const SEND_DEVICE_INFO = `${KEY}SEND_DEVICE_INFO`;
export const REQUEST_DEVICE_PUSH_ID = `${KEY}REQUEST_DEVICE_PUSH_ID`;
export const SEND_DEVICE_PUSH_ID = `${KEY}SEND_DEVICE_PUSH_ID`;
