const KEY = '@appqueueMiddleware/';

export const REQUEST_DEVICE_INFO = `${KEY}REQUEST_DEVICE_INFO`;
export const REQUEST_DEVICE_TOKEN = `${KEY}REQUEST_DEVICE_TOKEN`;
export const SEND_DEVICE_INFO = `${KEY}SEND_DEVICE_INFO`;
export const SEND_DEVICE_TOKEN = `${KEY}SEND_DEVICE_TOKEN`;
